name: Build README

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual update of README'
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 7-23/2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout project source code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Generate updated README file
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}

      - name: Commit and Push new README.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update README stats'
          file_pattern: 'README.md'
